"""create products table

Revision ID: 37659f55c1bc
Revises: dc29adf69dc7
Create Date: 2025-06-24 16:08:34.186043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37659f55c1bc'
down_revision: Union[str, None] = 'dc29adf69dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('products', 'name_product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name_product', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('products', 'title')
    # ### end Alembic commands ###
